### ISSUE TITLE
UI revamp needed

### ISSUE THREAD

**Issue by kushagra-singhh** [Saty70/QuesHai#3]
## Description :
The current UI is not very user-friendly.

## Suggested Fix : 
- Create new UI
- Material Design
- Easy to Navigate
- Less Scrolls

**Comment by Saty70** [comment]
feel free to contribute

**Comment by Trident09** [comment]
please assign this issue to me and kushagra, we would like to work on this

**Comment by Saty70** [comment]
Materialize the ui

**Comment by kushagra-singhh** [comment]
> Materialize the ui

no! my life my rules
